In [87]:
import pandas as pd
import numpy as np

In [88]:
train=pd.read_csv('trainf.csv')
test=pd.read_csv('test.csv')
# train2=pd.read_csv('mnist_train.csv')

In [89]:
# train=pd.concat([train1,train2],axis=1)

In [90]:
print(train.shape,test.shape)

(102000, 785) (28000, 784)

In [91]:
print(train.columns)
print()
print(test.columns)

Index(['label', 'pixel0', 'pixel1', 'pixel2', 'pixel3', 'pixel4', 'pixel5',
       'pixel6', 'pixel7', 'pixel8',
       ...
       'pixel774', 'pixel775', 'pixel776', 'pixel777', 'pixel778', 'pixel779',
       'pixel780', 'pixel781', 'pixel782', 'pixel783'],
      dtype='object', length=785)

Index(['pixel0', 'pixel1', 'pixel2', 'pixel3', 'pixel4', 'pixel5', 'pixel6',
       'pixel7', 'pixel8', 'pixel9',
       ...
       'pixel774', 'pixel775', 'pixel776', 'pixel777', 'pixel778', 'pixel779',
       'pixel780', 'pixel781', 'pixel782', 'pixel783'],
      dtype='object', length=784)

In [92]:
train.head()

,label,pixel0,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,...,pixel774,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783
0,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,4,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [93]:
test.head()

,pixel0,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,pixel9,...,pixel774,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [94]:
x=train.drop(['label'],axis=1)
y=train['label']

In [95]:
x

,pixel0,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,pixel9,...,pixel774,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101995,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
101996,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
101997,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
101998,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
101999,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [96]:
from sklearn.feature_selection import SelectKBest, chi2,f_classif,mutual_info_classif
# your data X and target y

# create the selector
selector = SelectKBest(chi2, k=500)

# fit the selector to your data
selector.fit(x, y)

# get the selected features
selected_features = selector.transform(x)
sel=selector.get_support()
x=x.loc[:,sel]
x

,pixel66,pixel67,pixel68,pixel69,pixel70,pixel71,pixel72,pixel73,pixel74,pixel75,...,pixel742,pixel743,pixel744,pixel745,pixel746,pixel747,pixel768,pixel769,pixel770,pixel771
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101995,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
101996,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
101997,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
101998,0,0,0,0,0,0,0,0,55,192,...,0,0,0,0,0,0,0,0,0,0
101999,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [97]:
y

0         1
1         0
2         1
3         4
4         0
         ..
101995    8
101996    3
101997    5
101998    6
101999    8
Name: label, Length: 102000, dtype: int64

In [98]:

import lightgbm as lgb
import optuna
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
xtrain, xtest, ytrain, ytest = train_test_split(x, y, test_size=0.2, random_state=42)

In [99]:
import catboost as cb

In [100]:
# cat=cb.CatBoostClassifier()
# cat.fit(xtrain,ytrain)
# pred=cat.predict(xtest)
# accuracy_score(ytest,pred)

In [101]:
from sklearn.model_selection import GridSearchCV
import lightgbm as lgb
lgb=lgb.LGBMClassifier()
lgb.fit(xtrain,ytrain)
pred=lgb.predict(xtest)
accuracy_score(ytest,pred)

0.9889705882352942

In [102]:
# # selector.fit(test)
test=test.loc[:,sel]
test

,pixel66,pixel67,pixel68,pixel69,pixel70,pixel71,pixel72,pixel73,pixel74,pixel75,...,pixel742,pixel743,pixel744,pixel745,pixel746,pixel747,pixel768,pixel769,pixel770,pixel771
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27995,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
27996,0,0,0,0,0,0,0,0,0,0,...,51,253,183,0,0,0,0,0,51,252
27997,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
27998,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
27999,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [103]:
pred=lgb.predict(test)

In [104]:
pred

array([2, 0, 9, ..., 3, 9, 2], dtype=int64)

In [105]:
c=pd.read_csv('sample_submission.csv')
c.head()

   ImageId  Label
0        1      0
1        2      0
2        3      0
3        4      0
4        5      0

In [106]:
c['Label']=pred

In [107]:
c

       ImageId  Label
0            1      2
1            2      0
2            3      9
3            4      0
4            5      3
...        ...    ...
27995    27996      9
27996    27997      7
27997    27998      3
27998    27999      9
27999    28000      2

[28000 rows x 2 columns]

In [108]:
c.to_csv('selk.csv',index=False)